trigger:
  branches:
    include:
      - main

schedules:
  - cron: "23 * * *"  # Runs at 23 PM UTC every day
    displayName: Daily build
    branches:
      include:
        - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    pip install azure-mgmt-security
    python pull_sentinel_incidents.py
  displayName: 'Run Python script to pull Sentinel incidents'

- task: SendEmail@1
  inputs:
    To: 'sharedmailbox@example.com'
    Subject: 'Daily Azure Sentinel Incidents'
    Body: 'Please find the attached incidents report.'
    Attachments: 'incidents_report.csv'
  displayName: 'Send email with incidents report'

